# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85ec664f3d1c41ab0db385484fa480f16ce02579d9a8bc466ac7012f699111a814aae1e3bd16189af3b9ca368096aef12889e55f399b6561d62e21e185738334

test:
  secret_key_base: ca4f622a86a168b674e49b328e6692bd69c8efe6a0e94ade8f88edcd6ad1e601e53aa2a30e43978f507d62350d14234aa49078536d0f52491f87b6dbff576071

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
